### ISSUE TITLE
Review browserslist

### ISSUE THREAD

**Issue by palexcast** [sosialkontoret/vinlotteriet#33]
Current `browserslist` supports these browsers:
Run `npx browserslist` to see list.

```
and_chr 91
and_ff 89
and_qq 10.4
and_uc 12.12
android 91
baidu 7.12
chrome 91
chrome 90
edge 91
edge 90
firefox 89
firefox 88
firefox 78
ios_saf 14.5-14.7
ios_saf 14.0-14.4
ios_saf 13.4-13.7
kaios 2.5
op_mini all
op_mob 62
opera 77
opera 76
safari 14.1
safari 14
samsung 14.0
samsung 13.0
```

I'm not sure what all these are, but it does trigger es5 to be built. 
Which we might not wish.

@boyum Thoughts?

**Comment by boyum** [comment]
I think op_mini might be the problem. We should try adding `not op_mini` to the config.
